module: CoolDownParser

author: techprimate GmbH & Co. KG
author_url: https://github.com/techprimate
copyright: '© 2021 [techprimate GmbH & Co. KG](https://techprimate.com). All rights reserved.'
github_url: https://github.com/techprimate/CoolDown

theme: fullwidth

separate_global_declarations: true
use_safe_filenames: true

swift_build_tool: spm
include: Sources/**

